ncol(DB_TER)
nrow(DB_TER)
str(DB_TER)
summary(DB_TER)
RA_TER = subset(DB_TER, Région=="Rhône Alpes")
summary(RA_TER)
DB_TER$Annee <- substr(DB_TER$Date, 1, 4)
DB_TER$Mois <- substr(DB_TER$Date, 6,7)
tapply(DB_TER$Taux.de.régularité, DB_TER$Région, mean)
aggregate(DB_TER$Taux.de.régularité, list(DB_TER$Région), mean)
tapply(DB_TER$Nombre.de.trains.programmés, DB_TER$Région, mean)